### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Aujulyn**
Will need some merging with Philip's changes to StoreFrame.
Untested.

### CODE REVIEW

**Comment by pandanii** [comment]
To make yours compatible with Philips just go too
https://github.com/pandanii/booksRus/pull/8/files, set to split in the top
right, and compare the green with the red.

check the StoreFrame file.

You'll most likely want to add the red into your file, OR alternatively you
can put your green into the new master file.

**Comment by Aujulyn** [comment]
I've already created a new pull request which fixed a few quick bugs with
the addUserJDialog. link to that one?

**Comment by pandanii** [comment]
https://github.com/pandanii/booksRus/pull/9/commits/89dbe2cfe7dbce06b5634417c1f1c7330d6cffe1

**Comment by Aujulyn** [comment]
So I have to modify my code with his changes I'm guessing? I had thought
Git might make it easy to select which changes to keep, or am I just not
seeing that functionality?

**Comment by pandanii** [comment]
Dunno, haven't looked into it that much, didnt need it until now. You could
look if you want.

**Pull request closed without merging**
